"""Dependency policy tables for probe environment preparation."""

from __future__ import annotations


PACKAGE_TO_MODULE = {
    "amqp": "amqp",
    "atpublic": "public",
    "attrs": "attr",
    "docstring-parser": "docstring_parser",
    "execnet": "execnet",
    "face": "face",
    "filelock": "filelock",
    "html5tagger": "html5tagger",
    "httptools": "httptools",
    "libsass": "sass",
    "msgspec": "msgspec",
    "multidict": "multidict",
    "mypy-extensions": "mypy_extensions",
    "platformdirs": "platformdirs",
    "public": "public",
    "pydantic-settings": "pydantic_settings",
    "pyyaml": "yaml",
    "pyproject-hooks": "pyproject_hooks",
    "pytest": "pytest",
    "python-discovery": "python_discovery",
    "python-frontmatter": "frontmatter",
    "python-multipart": "multipart",
    "sanic-testing": "sanic_testing",
    "sanic-ext": "sanic_ext",
    "sanic-routing": "sanic_routing",
    "scikit-learn": "sklearn",
    "sqlalchemy": "sqlalchemy",
    "tracerite": "tracerite",
    "ujson": "ujson",
    "urwid": "urwid",
    "w3lib": "w3lib",
}

HEAVY_OR_EXTERNAL = {"akshare", "yfinance", "tushare", "xgboost", "lightgbm", "fredapi", "mcp"}
NATIVE_OR_COMPILED = {"bcrypt", "httptools", "libsass", "lxml", "msgspec", "multidict", "pycurl", "pyyaml", "ujson"}
WHEEL_ONLY_NATIVE_ALLOWLIST = {"httptools", "libsass", "lxml", "msgspec", "multidict", "pyyaml", "ujson"}
PACKAGE_COMPANIONS = {"sanic-ext": ["pydantic"]}
LOW_RISK_ALLOWLIST = {
    "aiofiles",
    "aiohttp",
    "amqp",
    "atpublic",
    "attrs",
    "astroid",
    "boltons",
    "botocore",
    "click",
    "cssselect",
    "docstring-parser",
    "execnet",
    "face",
    "fastapi",
    "filelock",
    "flask",
    "html5tagger",
    "httpx",
    "invoke",
    "jmespath",
    "kombu",
    "loguru",
    "mako",
    "mistune",
    "mypy-extensions",
    "packaging",
    "pathspec",
    "platformdirs",
    "public",
    "pydantic",
    "pydantic-settings",
    "pygments",
    "pyproject-hooks",
    "pytest",
    "python-discovery",
    "python-frontmatter",
    "python-multipart",
    "rich",
    "sanic-testing",
    "sanic-ext",
    "sanic-routing",
    "shellingham",
    "sqlalchemy",
    "stevedore",
    "tomli",
    "tracerite",
    "typing-extensions",
    "urwid",
    "uvicorn",
    "userpath",
    "websockets",
    "w3lib",
}

INTERNAL_PROBE_STUBS = {"static_http_route_fallback", "static_shape_fallback"}
